[package]
name = "synosearch"
version = "0.0.1"
authors = []
edition = "2018"

[dependencies]
reqwest={ version = "0.11.3", features = ["blocking"] }
actix = "0.11.1"
actix-rt = "2.0"
std-semaphore="0.1.0"
